<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
	<TargetFrameworks>net48</TargetFrameworks>
	<PlatformTarget>AnyCPU</PlatformTarget>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	<EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
	<RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace("-", "_"))</RootNamespace>
	<NoWarn>CA1416</NoWarn>

	<OutputPath>bin\</OutputPath>
	<StartupObject></StartupObject>
	<OutputType>Library</OutputType>
	<RunCommand>$(ProgramFiles)\IIS Express\iisexpress.exe</RunCommand>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	<RunArguments>/config:".\Properties\applicationhost.config"</RunArguments>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net48|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net48|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <ItemGroup>
	<Reference Include="System.Configuration" />
	<Reference Include="System.Web" />
	<Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <ItemGroup>
	<Compile Update="Global.asax.cs">
	  <DependentUpon>Global.asax</DependentUpon>
	</Compile>
	<Compile Update="Properties\Resources.Designer.cs">
	  <DesignTime>True</DesignTime>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Resources.resx</DependentUpon>
	</Compile>
	<Compile Update="Properties\Settings.Designer.cs">
	  <DesignTimeSharedInput>True</DesignTimeSharedInput>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Settings.settings</DependentUpon>
	</Compile>
  </ItemGroup>
  <ItemGroup>
	<Content Include="App_Data\AspNetAuthentication-20180620032016.mdf" />
	<Content Include="App_Data\AspNetAuthentication-20180620032016_log.ldf">
	  <DependentUpon>AspNetAuthentication-20180620032016.mdf</DependentUpon>
	</Content>
	<Content Include="Content\bootstrap.css" />
	<Content Include="Content\bootstrap.min.css" />
	<Content Include="favicon.ico" />
	<Content Include="fonts\glyphicons-halflings-regular.svg" />
	<Content Include="Global.asax" />
	<Content Include="Content\Site.css" />
	<Content Include="Scripts\bootstrap.js" />
	<Content Include="Scripts\bootstrap.min.js" />
	<Content Include="Scripts\jquery-1.10.2.js" />
	<Content Include="Scripts\jquery-1.10.2.min.js" />
	<Content Include="Scripts\jquery.validate.js" />
	<Content Include="Scripts\jquery.validate.min.js" />
	<Content Include="Scripts\jquery.validate.unobtrusive.js" />
	<Content Include="Scripts\jquery.validate.unobtrusive.min.js" />
	<Content Include="Scripts\modernizr-2.6.2.js" />
	<Content Include="Scripts\respond.js" />
	<Content Include="Scripts\respond.min.js" />
	<Content Include="Scripts\_references.js" />
  </ItemGroup>
  <ItemGroup>
	<Content Include="fonts\glyphicons-halflings-regular.woff" />
	<Content Include="fonts\glyphicons-halflings-regular.ttf" />
	<Content Include="fonts\glyphicons-halflings-regular.eot" />
	<Content Include="Scripts\jquery-1.10.2.min.map" />
  </ItemGroup>
  <ProjectExtensions>
	<VisualStudio>
	  <FlavorProperties GUID="{349c5851-65df-11da-9384-00065b846f21}">
		<WebProjectProperties>
		  <UseIIS>True</UseIIS>
		  <AutoAssignPort>True</AutoAssignPort>
		  <DevelopmentServerPort>24478</DevelopmentServerPort>
		  <DevelopmentServerVPath>/</DevelopmentServerVPath>
		  <IISUrl>http://localhost:24478/</IISUrl>
		  <NTLMAuthentication>False</NTLMAuthentication>
		  <UseCustomServer>False</UseCustomServer>
		  <CustomServerUrl></CustomServerUrl>
		  <SaveServerSettingsInUserFile>False</SaveServerSettingsInUserFile>
		</WebProjectProperties>
	  </FlavorProperties>
	</VisualStudio>
  </ProjectExtensions>
  <ItemGroup>
	<PackageReference Include="Antlr" />
	<PackageReference Include="bootstrap" />
	<PackageReference Include="EntityFramework" />
	<PackageReference Include="jQuery" />
	<PackageReference Include="jQuery.Validation" />
	<PackageReference Include="Microsoft.AspNet.Identity.Core" />
	<PackageReference Include="Microsoft.AspNet.Identity.EntityFramework" />
	<PackageReference Include="Microsoft.AspNet.Identity.Owin" />
	<PackageReference Include="Microsoft.AspNet.Mvc" />
	<PackageReference Include="Microsoft.AspNet.Razor" />
	<PackageReference Include="Microsoft.AspNet.Web.Optimization" />
	<PackageReference Include="Microsoft.AspNet.WebPages" />
	<PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" />
	<PackageReference Include="Microsoft.CSharp" />
	<PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" />
	<PackageReference Include="Microsoft.Net.Compilers" />
	<PackageReference Include="Microsoft.Owin" />
	<PackageReference Include="Microsoft.Owin.Host.SystemWeb" />
	<PackageReference Include="Microsoft.Owin.Security" />
	<PackageReference Include="Microsoft.Owin.Security.Cookies" />
	<PackageReference Include="Microsoft.Owin.Security.Facebook" />
	<PackageReference Include="Microsoft.Owin.Security.Google" />
	<PackageReference Include="Microsoft.Owin.Security.MicrosoftAccount" />
	<PackageReference Include="Microsoft.Owin.Security.OAuth" />
	<PackageReference Include="Microsoft.Owin.Security.Twitter" />
	<PackageReference Include="Microsoft.Web.Infrastructure" />
	<PackageReference Include="Modernizr" />
	<PackageReference Include="Newtonsoft.Json" />
	<PackageReference Include="Owin" />
	<PackageReference Include="Respond" />
	<PackageReference Include="System.ComponentModel.Annotations" />
	<PackageReference Include="WebGrease" />
	<PackageReference Include="Wisej-3" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>