<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net8.0'">
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<UserSecretsId>f1af2bdc-ec26-434e-b848-c95c8ebd6421</UserSecretsId>
		<StartupObject>$(RootNamespace).Startup</StartupObject>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Web.config" />
		<Content Remove="Web.Debug.config" />
		<Content Remove="Web.Release.config" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="App_Data\chinook.db" />
		<None Remove="App_Data\chinook.master.db" />
		<None Remove="Default.html" />
		<None Remove="favicon.ico" />
		<None Remove="Files\sample-mp4-file.mp4" />
		<None Remove="Files\Wisej-Datasheet-V2.3.pdf" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="App_Data\chinook.db">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="App_Data\chinook.master.db">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Default.html">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="favicon.ico">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Files\sample-mp4-file.mp4">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Files\Wisej-Datasheet-V2.3.pdf">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Themes\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Web.config">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Include="Web.Debug.config" />
		<None Include="Web.Release.config" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Default.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.14" />
		<PackageReference Include="System.Data.SQLite" Version="1.0.115.5" />
		<PackageReference Include="System.Data.SQLite.Core" Version="1.0.115.5" />
		<PackageReference Include="System.Data.SQLite.EF6" Version="1.0.115.5" />
		<PackageReference Include="System.Data.SQLite.Linq" Version="1.0.115.5" />
	</ItemGroup>

  <ItemGroup>
	<PackageReference Include="Wisej-4" Version="4.0.*-*" />
	<PackageReference Include="Wisej-4-BootstrapIcons" Version="4.0.*-*" />
    <PackageReference Include="Wisej-4-CKEditor" Version="4.0.*-*" />
    <PackageReference Include="Wisej-4-BingWallpaper" Version="4.0.*-*" />
    <PackageReference Include="Wisej-4-JustGage" Version="4.0.*-*" />
    <PackageReference Include="Wisej-4-Speech" Version="4.0.*-*" />
    <PackageReference Include="Wisej-4-CoolClock" Version="4.0.*-*" />
    <PackageReference Include="Wisej-4-ProgressCircle" Version="4.0.*-*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

	<ItemGroup>
		<None Update="chinookDataSet.xsc">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="chinookDataSet.xsd">
			<Generator>MSDataSetGenerator</Generator>
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
		<None Update="chinookDataSet.xss">
			<CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
</Project>
